from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Float, BigInteger, SmallInteger, DateTime, Integer, TIMESTAMP, NVARCHAR, VARCHAR

ItemModel = declarative_base()

class Item(ItemModel):
    __tablename__ = 'Az_product'
    AzItemId = Column('Product_id', NVARCHAR(128), primary_key=True)
    item_name = Column('item-name', NVARCHAR(1024), default='')
    item_description = Column('item-description', NVARCHAR(2048), default='')
    listing_id = Column('listing-id', VARCHAR(64), default='')
    seller_sku = Column('seller-sku', VARCHAR(64), default='')
    price = Column('price', Float, default=0.0)
    quantity = Column('quantity', Integer, default=0)
    open_date = Column('open-date', NVARCHAR(64), default='')
    image_url = Column('image-url', NVARCHAR(256), default='')
    item_is_marketplace = Column('item-is-marketplace', VARCHAR(16), default='')
    product_id_type = Column('product-id-type', VARCHAR(16), default='')
    zshop_shipping_fee = Column('zshop-shipping-fee', Float, default=0.0)
    item_note = Column('item-note', NVARCHAR(256), default='')
    item_condition = Column('item-condition', NVARCHAR(64), default='')
    zshop_category1 = Column('zshop-category1', NVARCHAR(32), default='')
    zshop_browse_path = Column('zshop-browse-path', NVARCHAR(32), default='')
    zshop_storefront_feature = Column('zshop-storefront-feature', NVARCHAR(32), default='')
    asin1 = Column('asin1', NVARCHAR(32), default='')
    asin2 = Column('asin2', NVARCHAR(32), default='')
    asin3 = Column('asin3', NVARCHAR(32), default='')
    will_ship_internationally = Column('will-ship-internationally', VARCHAR(16), default='')
    expedited_shipping = Column('expedited-shipping', VARCHAR(16), default='')
    zshop_boldface = Column('zshop-boldface', NVARCHAR(32), default='')
    product_id = Column('product-id', NVARCHAR(64), default='')
    bid_for_featured_placement = Column('bid-for-featured-placement', NVARCHAR(32), default='')
    add_delete = Column('add-delete', NVARCHAR(32), default='')
    pending_quantity = Column('pending-quantity', Integer, default=0)
    fulfillment_channel = Column('fulfillment-channel', NVARCHAR(16), default='')
    merchant_shipping_group = Column('merchant-shipping-group', NVARCHAR(32), default='')
    status = Column('status', NVARCHAR(32), default='')
    # Only used for creating table
    # Stamp = Column('Stamp', TIMESTAMP)
    StoreId = Column('Store_id', BigInteger, default=0)
    UpdateStatus = Column('Update_status', SmallInteger, default=10)
    AmiStatus = Column('Ami_status', Integer, default=0)
    PluginCreateTime = Column('Plugin_create_time', DateTime, default='')
    PluginUpdateTime = Column('Plugin_update_time', DateTime, default='')