from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Float, BigInteger, SmallInteger, DateTime, Integer, TIMESTAMP, NVARCHAR, VARCHAR

ReturnModel = declarative_base()

class SfReturnHead(ReturnModel):
    __tablename__ = 'Sf_return_head'
    ReturnHeadId = Column('Order_head_id', NVARCHAR(128), primary_key=True)
    id = Column('id', NVARCHAR(32), default='')
    order_id = Column('order_id', NVARCHAR(32), default='')
    created_at = Column('created_at', NVARCHAR(32), default='')
    note = Column('note', NVARCHAR(128), default='')
    user_id = Column('user_id', NVARCHAR(32), default='')
    processed_at = Column('processed-at', NVARCHAR(32), default='')
    restock = Column('restock', NVARCHAR(16), default='')
    admin_graphql_api_id = Column('admin_graphql_api_id', NVARCHAR(128), default='')
    # Stamp = Column('Stamp', TIMESTAMP)
    StoreId = Column('Store_id', BigInteger, default=0)
    UpdateStatus = Column('Update_status', SmallInteger, default=1)
    AmiStatus = Column('Ami_status', Integer, default=0)
    PluginCreateTime = Column('Plugin_create_time', DateTime, default='')
    PluginUpdateTime = Column('Plugin_update_time', DateTime, default='')

class SfReturnLine(ReturnModel):
    __tablename__ = 'Sf_return_line'
    ReturnLineId = Column('Order_line_id', NVARCHAR(128), primary_key=True)
    ReturnHeadId = Column('Order_head_id', NVARCHAR(128), default='')
    id = Column('id', NVARCHAR(32), default='')
    quantity = Column('quantity', Integer, default=0)
    line_item_id = Column('line_item_id', NVARCHAR(32), default='')
    location_id = Column('location_id', NVARCHAR(32), default='')
    restock_type = Column('restock_type', NVARCHAR(16), default='')
    subtotal = Column('subtotal', Float, default=0.0)
    total_tax = Column('total_tax', Float, default=0.0)
    subtotal_set_shop_money_amount = Column('subtotal_set_shop_money_amount', Float, default=0.0)
    subtotal_set_shop_money_currency_code = Column('subtotal_set_shop_money_currency_code', NVARCHAR(16), default='')
    subtotal_set_presentment_money_amount = Column('subtotal_set_presentment_money_amount', Float, default=0.0)
    subtotal_set_presentment_money_currency_code = Column('subtotal_set_presentment_money_currency_code', NVARCHAR(16), default='')
    total_tax_set_shop_money_amount = Column('total_tax_set_shop_money_amount', Float, default=0.0)
    total_tax_set_shop_money_currency_code = Column('total_tax_set_shop_money_currency_code', NVARCHAR(16), default='')
    total_tax_set_presentment_money_amount = Column('total_tax_set_presentment_money_amount', Float, default=0.0)
    total_tax_set_presentment_money_currency_code = Column('total_tax_set_presentment_money_currency_code', NVARCHAR(16), default='')
    line_item_id = Column('line_item_id', NVARCHAR(32), default='')
    line_item_variant_id = Column('line_item_variant_id', NVARCHAR(32), default='')
    line_item_title = Column('line_item_title', NVARCHAR(128), default='')
    line_item_quantity = Column('line_item_quantity', Integer, default=0)
    line_item_sku = Column('line_item_sku', NVARCHAR(32), default='')
    line_item_variant_title = Column('line_item_variant_title', NVARCHAR(128), default='')
    line_item_vendor = Column('line_item_vendor', NVARCHAR(64), default='')
    line_item_fulfillment_service = Column('line_item_fulfillment_service', NVARCHAR(32), default='')
    line_item_product_id = Column('line_item_product_id', NVARCHAR(32), default='')
    line_item_requires_shipping = Column('line_item_requires_shipping', NVARCHAR(16), default='')
    line_item_taxable = Column('line_item_taxable', NVARCHAR(16), default='')
    line_item_gift_card = Column('line_item_gift_card', NVARCHAR(16), default='')
    line_item_name = Column('line_item_name', NVARCHAR(64), default='')
    line_item_variant_inventory_management = Column('line_item_variant_inventory_management', NVARCHAR(16), default='')
    line_item_product_exists = Column('line_item_product_exists', NVARCHAR(16), default='')
    line_item_fulfillable_quantity = Column('line_item_fulfillable_quantity', Integer, default=0)
    line_item_grams = Column('line_item_grams', Integer, default=0)
    line_item_price = Column('line_item_price', Float, default=0.0)
    line_item_total_discount = Column('line_item_total_discount', Float, default=0.0)
    line_item_fulfillment_status = Column('line_item_fulfillment_status', NVARCHAR(16), default='')
    line_item_price_set_shop_money_amount = Column('line_item_price_set_shop_money_amount', Float, default=0.0)
    line_item_price_set_shop_money_currency_code = Column('line_item_price_set_shop_money_currency_code', NVARCHAR(16), default='')
    line_item_price_set_presentment_money_amount = Column('line_item_price_set_presentment_money_amount', Float, default=0.0)
    line_item_price_set_presentment_money_currency_code = Column('line_item_price_set_presentment_money_currency_code', NVARCHAR(16), default='')
    line_item_total_discount_set_shop_money_amount = Column('line_item_total_discount_set_shop_money_amount', Float, default=0.0)
    line_item_total_discount_set_shop_money_currency_code = Column('line_item_total_discount_set_shop_money_currency_code', NVARCHAR(16), default='')
    line_item_total_discount_set_presentment_money_amount = Column('line_item_total_discount_set_presentment_money_amount', Float, default=0.0)
    line_item_total_discount_set_presentment_money_currency_code = Column('line_item_total_discount_set_presentment_money_currency_code', NVARCHAR(16), default='')
    line_item_admin_graphql_api_id = Column('line_item_admin_graphql_api_id', NVARCHAR(128), default='')