from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Float, BigInteger, SmallInteger, DateTime, Integer, TIMESTAMP, NVARCHAR, VARCHAR

OrderModel = declarative_base()


class OrderHead(OrderModel):
    __tablename__ = 'Afd_order_head'
    OrderHeadId = Column('Order_head_id', NVARCHAR(128), primary_key=True)
    acceptance_decision_date = Column('acceptance_decision_date', NVARCHAR(32), default='')
    can_cancel = Column('can_cancel', VARCHAR(16), default='')
    channel = Column('channel', NVARCHAR(32), default='')
    commercial_id = Column('commercial_id', NVARCHAR(32), default='')
    created_date = Column('created_date', NVARCHAR(32), default='')
    currency_iso_code = Column('currency_iso_code', NVARCHAR(16), default='')
    billing_address_city = Column('billing_address_city', NVARCHAR(32), default='')
    billing_address_company = Column('billing_address_company', NVARCHAR(64), default='')
    billing_address_country = Column('billing_address_country', NVARCHAR(32), default='')
    billing_address_country_iso_code = Column('billing_address_country_iso_code', NVARCHAR(64), default='')
    billing_address_firstname = Column('billing_address_firstname', NVARCHAR(64), default='')
    billing_address_lastname = Column('billing_addresslast_name', NVARCHAR(64), default='')
    billing_address_phone = Column('billing_address_phone', NVARCHAR(64), default='')
    billing_address_phone_secondary = Column('billing_address_phone_secondary', NVARCHAR(64), default='')
    billing_address_state = Column('billing_address_state', NVARCHAR(64), default='')
    billing_address_street_1 = Column('billing_address_street_1', NVARCHAR(64), default='')
    billing_address_street_2 = Column('billing_address_street_2', NVARCHAR(64), default='')
    billing_address_zip_code = Column('billing_address_zip_code', NVARCHAR(64), default='')
    civility = Column('civility', NVARCHAR(16), default='')
    customer_id = Column('customer_id', NVARCHAR(64), default='')
    firstname = Column('first_name', NVARCHAR(32), default='')
    lastname = Column('last_name', NVARCHAR(32), default='')
    locale = Column('locale', NVARCHAR(16), default='')
    shipping_address_additional_info = Column('shipping_address_additional_info', NVARCHAR(32), default='')
    shipping_address_city = Column('shipping_address_city', NVARCHAR(32), default='')
    shipping_address_company = Column('shipping_address_company', NVARCHAR(64), default='')
    shipping_address_country = Column('shipping_address_country', NVARCHAR(32), default='')
    shipping_address_country_iso_code = Column('shipping_address_country_iso_code', NVARCHAR(64), default='')
    shipping_address_firstname = Column('shipping_address_firstname', NVARCHAR(64), default='')
    shipping_address_lastname = Column('shipping_address_lastname', NVARCHAR(64), default='')
    shipping_address_phone = Column('shipping_address_phone', NVARCHAR(32), default='')
    shipping_address_phone_secondary = Column('shipping_address_phone_secondary', NVARCHAR(32), default='')
    shipping_address_state = Column('shipping_address_state', NVARCHAR(32), default='')
    shipping_address_street_1 = Column('shipping_address_street_1', NVARCHAR(64), default='')
    shipping_address_street_2 = Column('shipping_address_street_2', NVARCHAR(64), default='')
    shipping_address_zip_code = Column('shipping_address_zip_code', NVARCHAR(32), default='')
    customer_debited_date = Column('customer_debited_date', NVARCHAR(32), default='')
    has_customer_message = Column('has_customer_message', VARCHAR(16), default='')
    has_incident = Column('has_incident', VARCHAR(16), default='')
    has_invoice = Column('has_invoice', VARCHAR(16), default='')
    last_updated_date = Column('last_updated_date', NVARCHAR(32), default='')
    leadtime_to_ship = Column('leadtime_to_ship', NVARCHAR(32), default='')
    order_id = Column('order_id', NVARCHAR(32), default='', index=True)
    order_state = Column('order_state', VARCHAR(32), default='')
    order_state_reason_code = Column('order_state_reason_code', NVARCHAR(32), default='')
    order_state_reason_label = Column('order_state_reason_label', NVARCHAR(32), default='')
    paymentType = Column('paymentType', NVARCHAR(32), default='')
    payment_type = Column('payment_type', NVARCHAR(32), default='')
    payment_workflow = Column('payment_workflow', NVARCHAR(32), default='')
    price = Column('price', Float, default=0.0)
    total_deduced_amount = Column('total_deduced_amount', NVARCHAR(64), default='')
    quote_id = Column('quote_id', NVARCHAR(64), default='')
    shipping_carrier_code = Column('shipping_carrier_code', NVARCHAR(64), default='')
    shipping_company = Column('shipping_company', NVARCHAR(64), default='')
    shipping_price = Column('shipping_price', Float, default=0.0)
    shipping_tracking = Column('shipping_tracking', NVARCHAR(64), default='')
    shipping_tracking_url = Column('shipping_tracking_url', NVARCHAR(256), default='')
    shipping_type_code = Column('shipping_type_code', NVARCHAR(64), default='')
    shipping_type_label = Column('shipping_type_label', NVARCHAR(64), default='')
    shipping_zone_code = Column('shipping_zone_code', NVARCHAR(64), default='')
    shipping_zone_label = Column('shipping_zone_label', NVARCHAR(64), default='')
    total_commission = Column('total_commission', Float, default=0.0)
    total_price = Column('total_price', Float, default=0.0)
    # Only used for creating table
    # Stamp = Column('Stamp', TIMESTAMP)
    StoreId = Column('Store_id', BigInteger, default=0)
    UpdateStatus = Column('Update_status', SmallInteger, default=10, index=True)
    AmiStatus = Column('Ami_status', Integer, default=0)
    PluginCreateTime = Column('Plugin_create_time', DateTime, default='')
    PluginUpdateTime = Column('Plugin_update_time', DateTime, default='', index=True)


class OrderLine(OrderModel):
    __tablename__ = 'Afd_order_line'
    OrderLineId = Column('Order_line_id', NVARCHAR(128), primary_key=True)
    OrderHeadId = Column('Order_head_id', NVARCHAR(128))
    discount_amount = Column('discount_amount', Float, default=0.0)
    can_refund = Column('can_refund', VARCHAR(16), default='')
    category_code = Column('category_code', NVARCHAR(32), default='')
    category_label = Column('category_label', NVARCHAR(32), default='')
    commission_fee = Column('commission_fee', Float, default=0.0)
    commission_rate_vat = Column('commission_rate_vat', Float, default=0.0)
    commission_vat = Column('commission_vat', Float, default=0.0)
    created_date = Column('created_date', NVARCHAR(64), default='')
    debited_date = Column('debited_date', NVARCHAR(64), default='')
    description = Column('description', NVARCHAR(256), default='')
    last_updated_date = Column('last_updated_date', NVARCHAR(64), default='')
    offer_id = Column('offer_id', NVARCHAR(32), default='')
    offer_sku = Column('offer_sku', NVARCHAR(32), default='')
    offer_state_code = Column('offer_state_code', NVARCHAR(32), default='')
    Afd_order_line_id = Column('Afd_order_line_id', NVARCHAR(32), default='')
    order_line_index = Column('order_line_index', Integer, default=0)
    order_line_state = Column('order_line_state', VARCHAR(32), default='')
    order_line_state_reason_code = Column('order_line_state_reason_code', NVARCHAR(32), default='')
    order_line_state_reason_label = Column('order_line_state_reason_label', NVARCHAR(32), default='')
    price = Column('price', Float, default=0.0)
    price_additional_info = Column('price_additional_info', NVARCHAR(64), default='')
    price_unit = Column('price_unit', Float, default=0.0)
    product_sku = Column('product_sku', NVARCHAR(32), default='')
    product_title = Column('product_title', NVARCHAR(64), default='')
    quantity = Column('quantity', Integer, default=0)
    received_date = Column('received_date', NVARCHAR(64), default='')
    shipped_date = Column('shipped_date', NVARCHAR(64), default='')
    shipping_price = Column('shipping_price', Float, default=0.0)
    shipping_price_additional_unit = Column('shipping_price_additional_unit', Float, default=0.0)
    shipping_price_unit = Column('shipping_price_unit', NVARCHAR(64), default='')
    total_commission = Column('total_commission', Float, default=0.0)
    total_price = Column('total_price', Float, default=0.0)